server:
  port: 8086
spring:
  application:
    name: uaa
  main:
    allow-bean-definition-overriding: true
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://192.168.126.129:3306/test?useUnicode=true&characterEncoding=UTF-8&socketTimeout=60000
    userName: root
    password: 851535

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka

redis:
  cluster:
    nodes: 192.168.126.129:7001,192.168.126.129:7002,192.168.126.129:7003,192.168.126.129:7004,192.168.126.129:7005,192.168.126.129:7006
    timeout: 60000
    maxAttempts: 3
    maxWaitMillis: 60000
    maxTotal: 10
    minIdle: 10
    maxIdle: 10

feign.hystrix.enabled: true