server:
  port: 8086
spring:
  application:
    name: uaa
  main:
    allow-bean-definition-overriding: true
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://192.168.56.131:3306/testdd?useUnicode=true&characterEncoding=UTF-8&socketTimeout=60000
    userName: root
    password: 851535

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

feign.hystrix.enabled: true