server:
  port: 8086
spring:
  application:
    name: uaa
  main:
    allow-bean-definition-overriding: true
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://10.11.1.52:3306/test?useUnicode=true&characterEncoding=UTF-8&socketTimeout=60000
    userName: root
    password: 851535

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka

feign.hystrix.enabled: true